---
sudo: required
dist: bionic
language: python
python:
  - "2.7"
services:
  - docker
before_install:
  - sudo apt-get -qq update
  - ./.travis/docker_config.sh
  - sudo systemctl restart docker
install:
  - pip install molecule[docker] ansible-lint flake8 testinfra
  # - pip install docker-py
script:
  - molecule test
