---
# docker-ce
# Copyright Nicola Musatti 2020.

- name: Enable the EPEL repository
  include_role:
    name: geerlingguy.repo-epel
  when: dockerce_platform != 'Fedora'

- name: Remove Red Hat distributed Docker
  yum:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-compose
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
  become: true

- name: "Install the required packages (CentOS 8)"
  dnf:
    name: "{{ packages }}"
  vars:
    packages:
      - ca-certificates
      - container-selinux
      - device-mapper-persistent-data
      - gcc
      - iptables
      - libcgroup
      - lvm2
      - yum-utils
  become: true
  when: dockerce_platform == 'CentOS8'

- name: "Install the required packages (Fedora)"
  dnf:
    name: "{{ packages }}"
  vars:
    packages:
      - ca-certificates
      - container-selinux
      - device-mapper-persistent-data
      - gcc
      - iptables
      - libcgroup
      - libxcrypt-compat
      - lvm2
      - yum-utils
  become: true
  when: dockerce_platform == 'Fedora'

- name: "Install the required packages (CentOS 7)"
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - ca-certificates
      - device-mapper-persistent-data
      - gcc
      - lvm2
      - yum-utils
  become: true
  when: dockerce_platform == 'CentOS7'

- name: Check if the official Docker yum repository is available
  stat:
    path: /etc/yum.repos.d/docker-ce.repo
  register: docker_repo

- name: Install the official Docker repository
  command: "yum-config-manager --add-repo https://download.docker.com/linux/{{ dockerce_distribution }}/docker-ce.repo"
  become: true
  when: docker_repo.stat.exists is defined and not docker_repo.stat.exists

- name: "Install Docker and dependencies"
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - containerd.io
      - docker-ce
      - docker-ce-cli
  become: true

- name: Create the docker group
  group:
    name: docker
    state: present
  become: true

- name: Check if the containerd override file exists
  stat:
    path: /etc/systemd/system/containerd.service.d/override.conf
  register: containerd_path
  when: dockerce_platform == 'CentOS8'

- name: Check if the overlay module is available
  command: /sbin/modprobe overlay
  ignore_errors: true
  register: modprobe_overlay
  when: dockerce_platform == 'CentOS8' and not containerd_path.stat.exists

- name: Create containerd service directory
  file:
    path: /etc/systemd/system/containerd.service.d
    state: directory
    mode: 0755
  become: true
  when: dockerce_platform == 'CentOS8' and not containerd_path.stat.exists and modprobe_overlay is failed

- name: Disable overlay dependency
  copy:
    content: |
      [Service]
      ExecStartPre=
    dest: /etc/systemd/system/containerd.service.d/override.conf
    mode: 0644
  become: true
  when: dockerce_platform == 'CentOS8' and not containerd_path.stat.exists and modprobe_overlay is failed

- name: Start the docker service
  service:
    name: docker
    enabled: true
    state: started
  become: true
  ignore_errors: true
  register: docker_start

- name: Reload the docker service
  service:
    name: docker
    enabled: true
    state: reloaded
  become: true
  when: docker_start is failed

- name: Install docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: 0755
  become: true
