---
# docker-ce
# Copyright Nicola Musatti 2020 - 2021.

- name: Install Docker CE (RedHat)
  ansible.builtin.include_tasks: "redhat/install.yml"
  when: ansible_os_family == "RedHat"

- name: Install Docker CE (Ubuntu)
  include_tasks: "ubuntu/install.yml"
  when: ansible_distribution == "Ubuntu"

- name: Create the docker group
  ansible.builtin.group:
    name: docker
    state: present
  become: true

- name: Check if the containerd override file exists
  ansible.builtin.stat:
    path: /etc/systemd/system/containerd.service.d/override.conf
  register: containerd_path
  when: dockerce_platform == 'EL8'

- name: Check if the overlay module is available
  ansible.builtin.command: /sbin/modprobe overlay
  ignore_errors: true
  register: modprobe_overlay
  when: dockerce_platform == 'EL8' and not containerd_path.stat.exists

- name: Create containerd service directory
  ansible.builtin.file:
    path: /etc/systemd/system/containerd.service.d
    state: directory
    mode: 0755
  become: true
  when: dockerce_platform == 'EL8' and not containerd_path.stat.exists and modprobe_overlay is failed

- name: Disable overlay dependency
  ansible.builtin.copy:
    content: |
      [Service]
      ExecStartPre=
    dest: /etc/systemd/system/containerd.service.d/override.conf
    mode: 0644
  become: true
  when: dockerce_platform == 'EL8' and not containerd_path.stat.exists and modprobe_overlay is failed

- name: Start the docker service
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started
  become: true
  ignore_errors: true
  register: docker_start

- name: Reload the docker service
  ansible.builtin.service:
    name: docker
    enabled: true
    state: reloaded
  become: true
  when: docker_start is failed

- name: Install docker-compose
  ansible.builtin.get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: 0755
  become: true
