---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: $TOX_ENVNAME
    # image: nmusatti/${TOX_ENVNAME}-pys-systemd
    image: nmusatti/${TOX_ENVNAME}-pys
    # command: /sbin/init
    pre_build_image: true
    privileged: true
    # cgroupns_mode: host
    volumes:
      # - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/run/docker.sock:/var/run/docker.sock
provisioner:
  name: ansible
verifier:
  name: testinfra
