---
# docker-ce
# Copyright Nicola Musatti 2021.

- name: Remove Ubuntu distributed Docker
  ansible.builtin.apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
  become: true

- name: "Install the required packages"
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
  become: true

- name: Check if the official Docker apt repository is available
  ansible.builtin.stat:
    path: /etc/apt/sources.list.d/docker.list
  register: docker_repo

- name: Install the official Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
  when: docker_repo.stat.exists is defined and not docker_repo.stat.exists

- name: Retrieve package architecture
  ansible.builtin.command: "dpkg --print-architecture"
  register: dpkg_architecture
  when: docker_repo.stat.exists is defined and not docker_repo.stat.exists

- name: Retrieve LSB release
  ansible.builtin.command: "lsb_release -cs"
  register: lsb_release
  when: docker_repo.stat.exists is defined and not docker_repo.stat.exists

- name: Install the official Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ dpkg_architecture.stdout }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
    {{ lsb_release.stdout }} stable"
    filename: docker
  become: true
  when: docker_repo.stat.exists is defined and not docker_repo.stat.exists

- name: "Install Docker and dependencies"
  ansible.builtin.apt:
    name:
      - containerd.io
      - docker-ce
      - docker-ce-cli
      - docker-buildx-plugin
      - docker-compose-plugin
  become: true
