on:
  push:
  pull_request:
  schedule:
  - cron: "0 6 1 * *"

name: test

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        platform:
          - rockylinux9
          - rockylinux8
          - centos7
          - centos-stream9
          - centos-stream8
          - fedora37
          - fedora36
          - fedora35
          - ubuntu2204
          - ubuntu2004
          - ubuntu1804
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: iptables
          version: 1.0
      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      - run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install tox
      - env:
          ANSIBLE_REMOTE_TMP: /tmp/ansible
        run: |
          tox -e ${{ matrix.platform }} -- test
